AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CloudFormation template for ComfyUI on Amazon SageMaker with synchronous and asynchronous endpoints

Parameters:
  AppName:
    Type: String
    Default: comfyui
  DeploymentBucket:
    Type: String
    Default: comfyui-on-sagemaker
  LambdaPackageS3Key:
    Type: String
    Default: lambda.zip
  ModelVersion:
    Type: String
    Default: default
  ModelDataS3Key:
    Type: String
    Default: model-data-comfyui-default.tgz
  ModelEcrImage:
    Type: String
    Default: comfyui-inference:default
  SageMakerInstanceType:
    Type: String
    AllowedValues:
      - ml.g4dn.xlarge
      - ml.g4dn.2xlarge
      - ml.g5.xlarge
      - ml.g5.2xlarge
      - ml.g5.4xlarge
      - ml.g5.8xlarge
      - ml.g5.16xlarge
      - ml.g5.12xlarge
      - ml.g5.24xlarge
      - ml.g5.48xlarge
      - ml.g6.xlarge
      - ml.g6.2xlarge
      - ml.g6.4xlarge
      - ml.g6.8xlarge
      - ml.g6.16xlarge
      - ml.g6.12xlarge
      - ml.g6.24xlarge
      - ml.g6.48xlarge
    Default: ml.g5.4xlarge
  LambdaUrlAuthType:
    Type: String
    AllowedValues:
      - NONE
      - AWS_IAM
    Default: AWS_IAM

Resources:
  ComfyUIModelExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AppName}-sagemaker-model-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: !Sub "${AppName}-sagemaker-async-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${DeploymentBucket}/async-outputs"
                  - !Sub "arn:aws:s3:::${DeploymentBucket}/async-outputs/*"

  ComfyUIAsyncModel:
    Type: "AWS::SageMaker::Model"
    Properties:
      EnableNetworkIsolation: true
      ExecutionRoleArn: !GetAtt ComfyUIModelExecutionRole.Arn
      ModelName: !Sub "${AppName}-async-${ModelVersion}"
      PrimaryContainer:
        Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ModelEcrImage}"
        ModelDataUrl: !Sub "s3://${DeploymentBucket}/${ModelDataS3Key}"

  ComfyUIAsyncEndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      EndpointConfigName: !Sub "${AppName}-async-${ModelVersion}"
      ProductionVariants:
        - VariantName: "AsyncVariant"
          ModelName: !GetAtt ComfyUIAsyncModel.ModelName
          InitialInstanceCount: 1
          InstanceType: !Ref SageMakerInstanceType
          ContainerStartupHealthCheckTimeoutInSeconds: 1200
      AsyncInferenceConfig:
        OutputConfig:
          S3OutputPath: !Sub "s3://${DeploymentBucket}/async-outputs/"
          KmsKeyId: "alias/aws/s3"
        ClientConfig:
          MaxConcurrentInvocationsPerInstance: 2

  ComfyUIAsyncEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub "${AppName}-async"
      EndpointConfigName: !GetAtt ComfyUIAsyncEndpointConfig.EndpointConfigName

Outputs:
  ComfyUIAsyncEndpoint:
    Description: ARN of asynchronous SageMaker endpoint
    Value: !Ref ComfyUIAsyncEndpoint
